# Generated by Django 2.0.5 on 2018-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FibonacciNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nth_term', models.IntegerField()),
                ('value', models.TextField()),
            ],
        ),
    ]
